#!/bin/bash

#########################################################################
# Script run in the each V-T directory by prep_uptild.sh script
# Reeds in the Random number generated MD seed
# and picks out nth configurations of MD pre_POSITIONS coordinates file
# where the nth confiruation is equal to the random seed plus an 
# additional random number between 1 and 100.
# The additional random numbers are generated by the number_random_script.sh
# random configs are specificied in 'l' and lambda TI parameters in 'lam'.
# Scripts preps the INCAR POTCAR POSCAR Prun.pbs AND KPOINTS for UP-sampling sanpshot.
#########################################################################

#MAXCOUNT=10
#count=1
#RANGE=100
lam="0.0 0.15 0.5 0.85 1.0"
dir=`pwd`
l="31 97 24 46 83"

cd $dir && echo in the directory $dir

for j in $lam; do
  cd lambda$j/proc && echo in the directory called lambda$j
  rm -r config*
  CEED=$(awk '{ if (NR==5) print $3 }' ../INCAR)
  rm x* 
  split -l 64 -d last100x64
  for i in $l; do
    mkdir config$i && cp x$i config$i/config$i.$CEED
    cp ../../high_input/* config$i/.
    cat config$i/head config$i/config$i.$CEED > config$i/POSCAR
  done
  rm x*

  cd $dir
done
echo DONE








#while [ "$count" -le $MAXCOUNT ]      # Generate 10 ($MAXCOUNT) random integers.
#do
#  number=$RANDOM
#  let "number %= $RANGE"
#  echo $number && echo $number > out.random_configs
#  let "count += 1"  # Increment count.
#done

#cat out.random_configs | var
#l="1 2 3 4 5 6 7 8 9 10"
#for i in $var; do
#  cp x$var random$var
#done
  
 
